services:
  server-dashboard:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - /proc/meminfo:/proc/meminfo:ro
      - /proc/stat:/proc/stat:ro
      - /mnt/media:/mnt/media:ro
    restart: unless-stopped
